import random

def get_joke():
    jokes = [
        "Why don't eggs tell jokes? They'd crack each other up!",
        "I don't trust stairs. They're always up to something.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "Why did the math book look sad? Because it had too many problems.",
        "I used to play piano by ear, but now I use my hands.",
        "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
        "What do you call fake spaghetti? An impasta!",
        "How does a penguin build its house? Igloos it together!",
        "Why did the coffee file a police report? It got mugged.",
        "Why did the bicycle fall over? Because it was two-tired!",
        "How do you organize a space party? You planet!",
        "Why don't skeletons fight each other? They don’t have the guts.",
        "I used to hate facial hair, but then it grew on me.",
        "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
        "What do you call cheese that isn’t yours? Nacho cheese.",
        "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the ocean say to the beach? Nothing, it just waved.",
        "Why do cows have hooves instead of feet? Because they lactose.",
        "What do you call a factory that makes okay products? A satisfactory.",
        "Why did the computer go to the doctor? It had a virus.",
        "Why can't you hear a pterodactyl go to the bathroom? Because the P is silent.",
        "What do you call an alligator in a vest? An investigator.",
        "I’m reading a book on anti-gravity. It’s impossible to put down!",
        "Want to hear a construction joke? Oh never mind, I’m still working on it.",
        "Why was the math teacher late to work? She took the rhombus.",
        "Did you hear about the kidnapping at school? It’s fine, he woke up.",
        "What do you call a fish wearing a bowtie? So-fish-ticated.",
        "Why did the cookie go to the hospital? Because it felt crummy.",
        "I told my computer I needed a break, and now it won’t stop sending me KitKat ads.",
        "Why don’t oysters donate to charity? Because they’re shellfish.",
        "What did one wall say to the other? I’ll meet you at the corner.",
        "Why did the man put his money in the blender? He wanted to make some liquid assets.",
        "Why did the picture go to jail? Because it was framed.",
        "I couldn’t figure out why the baseball kept getting bigger. Then it hit me.",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "Why did the banker switch careers? He lost interest.",
        "Why did the clock get a promotion? It was outstanding in its field.",
        "I used to be addicted to soap, but I’m clean now.",
        "I stayed up all night to see where the sun went, and then it dawned on me.",
        "Why did the man run around his bed? Because he was trying to catch up on sleep.",
        "What kind of shoes do ninjas wear? Sneakers.",
        "What’s brown and sticky? A stick.",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "Why did the orange stop? It ran out of juice.",
        "Did you hear the rumor about butter? Well, I’m not going to spread it.",
        "I got hit in the head with a can of soda. Luckily, it was a soft drink.",
        "How do you make a tissue dance? You put a little boogie in it.",
        "Why can’t your nose be 12 inches long? Because then it’d be a foot.",
        "What’s Forrest Gump’s password? 1forest1.",
        "Why did the barber win the race? He knew all the shortcuts.",
        "Why did the music teacher go to jail? Because she got caught with too many notes.",
        "I used to be a baker, but I couldn’t make enough dough.",
        "Why don’t scientists trust atoms? Because they make up everything.",
        "I would tell you a chemistry joke, but I know I wouldn’t get a reaction.",
        "Did you hear about the claustrophobic astronaut? He just needed a little space.",
        "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels!",
        "Why do chicken coops only have two doors? Because if they had four, they’d be chicken sedans!",
        "Parallel lines have so much in common. It’s a shame they’ll never meet.",
        "Why do bees have sticky hair? Because they use honeycombs!",
        "What did the buffalo say to his son when he left for college? Bison!"
    ]

    return random.choice(jokes)
